### ISSUE TITLE
Error when getting close to Ender Dragon

### ISSUE THREAD

**Issue by AlmostPanda** [steve4744/WhatIsThis#11]
Hi, I get this error when I get to end, would you mind to take a look please

server version: 
Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)

https://pastebin.com/A9ECDL1z

To reproduce:
1. Go to end
2. Get close to Ender Dragon

**Comment by steve4744** [comment]
Interesting...thanks for reporting this. Will get a fix out soon.

**Comment by steve4744** [comment]
Fixed in version 5.5.1 available here: https://github.com/steve4744/WhatIsThis/releases/download/v5.5.1/WhatIsThis-5.5.1.jar

**Comment by AlmostPanda** [comment]
Works great, but I think you forgot something to turn off, because our console is spammed with this 😄 

```
[12:38:05 INFO]: [WhatIsThis] type = VILLAGER
[12:38:05 INFO]: [WhatIsThis] name = Cleric
[12:38:05 INFO]: [WhatIsThis] key = minecraft:villager
[12:38:05 INFO]: [WhatIsThis] key.key = villager
[12:38:32 INFO]: [WhatIsThis] name = Ender Dragon
[12:38:32 INFO]: [WhatIsThis] key = minecraft:ender_dragon
[12:38:32 INFO]: [WhatIsThis] key.key = ender_dragon
[12:38:33 INFO]: [WhatIsThis] type = ENDER_DRAGON
```

**Comment by steve4744** [comment]
Crap....sorry about that. I've replaced the jar in the 5.5.1 release so hopefully that one doesn't have the debug messages.

**Comment by AlmostPanda** [comment]
perfect, thank you
